### ISSUE TITLE
Referencing interface operation declared later fails

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#804] opened 2022-08-02 21:34 UTC
```cadl
interface Sad {
  @doc("{}", Sad.one) // <- squiggle squiggle error invalid-ref Interface doesn't have member one
  op two(): void;
  op one(): void;
}

interface Happy {
  op one(): void;
  @doc("{}", Happy.one) // <- No issues here!
  op two(): void;
}
```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW50ZXJmYWNlIFNhZCB7CiAgQGRvYygie30iLMQTLm9uZSkgLy8gPC0gc3F1aWdnbGXJCQogIG9wIHR3bygpOiB2b2lkO8YSb25lyhJ9CgrKZUhhcHB5xWfQJ815xSfFe9NjfQ%3D%3D)

**Comment by johanste** [comment] 2022-08-02 21:36
Not sure if this is by design, but it feels wrong. It seem to work outside of an interface:
```
@doc("{}", one) // <- No issues here!
op two(): void;
op one(): void;
```

**Comment by timotheeguerin** [comment] 2022-10-19 17:42
Also applies to `model`

**Comment by bterlson** [comment] 2022-10-19 18:34
Presently, afaik, evaluation order outside of things with members is top-down unless something needs a type, in which case that type is checked, and as a result, you can't depend on the order of these things in the graph, e.g. I think the order of models for namespace.models is effectively random. Evaluation for things with members is top-down and I'm not sure changing that is a great idea? Worried about surprises in e.g. decorator evaluation order when later properties can all of a sudden start running before earlier properties. At least we would have to ensure that we preserve property ordering in the graph, and decide how the half-initialized world looks (maybe property names mapped to undefined to start with, that get filled in later?)

**Comment by allenjzhang** [comment] 2022-10-26 21:22
@nguerrera , should we/can we tackle this issue or just resolve as by design?

**Comment by nguerrera** [comment] 2022-10-26 21:32
@allenjzhang This seems like a design issue to me. Tagging it as such.  
*If* we decide to keep this behavior, it might be nice if we could adjust the error from "Interface doesn't have member" to "Cannot reference member declared after this one" or something.

**Comment by nguerrera** [comment] 2022-10-26 21:32
is

**Comment by markcowl** [comment] 2022-11-16 22:51
Prototype a solution to this in December / MQ

**Comment by markcowl** [comment] 2022-11-28 21:57
Closing for the implementation issues referenced

**Closed by markcowl** 2022-11-28 21:57 UTC
Labels: CADL Design, WS: Language Completeness
