### ISSUE TITLE
[compiler] `getEffectiveModelType` doesn't work when filter property of a model

### ISSUE THREAD

**Issue by msyyc** [microsoft/cadl#1511] opened 2023-01-06 02:17 UTC
cadl-python uses `getEffectiveModelType` with filter to filter `@header` property of a model:
- [cadl definition](https://github.com/Azure/azure-rest-api-specs/blob/905a6457b34b790b29a4829fe2c3ac8322244326/specification/cognitiveservices/OpenAI.Inference/models/completions.create.cadl#L129):
```
model Completion {
    @doc("Request ID for troubleshooting purposes")
    @header "apim-request-id": string;
```
- [cadl-pythnon](https://github.com/Azure/autorest.python/blob/554ff7120b67acc3b1ff1e845057771fb9f6d536/packages/cadl-python/src/emitter.ts#L234-L248)
```python
function getEffectiveSchemaType(program: Program, type: Model): Model {
    function isSchemaProperty(property: ModelProperty) {
        const headerInfo = getHeaderFieldName(program, property);
        const queryInfo = getQueryParamName(program, property);
        const pathInfo = getPathParamName(program, property);
        const statusCodeinfo = isStatusCode(program, property);
        return !(headerInfo || queryInfo || pathInfo || statusCodeinfo);
    }

    const effective = getEffectiveModelType(program, type, isSchemaProperty);
    if (effective.name) {
        return effective;
    }
    return type;
}
```
However, it returns original model without any change:
![image](https://user-images.githubusercontent.com/70930885/210916777-9f7e3bc9-b0b2-4aeb-b77b-56d52346e2f7.png)

After looking into the code, I think the problem is in `filterModelProperties`
https://github.com/microsoft/cadl/blob/3c208033fdeed48dfdf69bc3ac9248444ef2d875/packages/compiler/core/checker.ts#L5041-L5048

It shall not always return anonymous model even the input has a model name:
https://github.com/microsoft/cadl/blob/3c208033fdeed48dfdf69bc3ac9248444ef2d875/packages/compiler/core/checker.ts#L5066-L5074
I think the name shall be :
```js
name: model.name,
```
cc @iscai-msft @lmazuel

**Comment by nguerrera** [comment] 2023-01-09 23:04
It's confusing, but the intention is that the filter you are passing to getEffectiveModelType is one that you will also use to ignore properties elsewhere. The cadl-python code shown here looks copied from an older OpenAPI emitter version. It was calling isSchemaProperty when emitting a schema to not put headers and such in schemas. Cadl-python would need to do likewise. getEffectiveModelType does not create new named models, it only finds equivalent named models. The purpose of the filtering is not to necessarily remove all headers and such from the input but to handle cases like determining that `{ @header x: string } & Foo` being equivalent to Foo in a context where headers will ultimately not be considered part of the type.

The OpenAPI emitter has evolved to go through MetadataInfo which handles more behaviors and #1083 tracks documenting this.

**Comment by nguerrera** [comment] 2023-01-13 18:13
Whenever reviewing a model with an @header (or @path, @query, etc.), it's important to ask "does this property logically belong to this model?". Is "apim-request-id" logically part of a Completion? I suspect not. So the Cadl should be changed along the lines of your PR unless I'm mistaken about that.

We have had a lot of debate about the cases where a logical model has header/path/query property that does logically belong and how to handle it or even whether DPG should support this at all. But before diving into the debate, it's best to use a real example that actually has logically well-factored Cadl. One thing I will say is that a client generator is not required to mimic OpenAPI. OpenAPI would simply be incorrect to put a header in the body schema. That's against the definition of the body schema. But a client generator has more freedom. It's only absolute constraint is that it emits code that works and that could involve a single class that transmits some of its properties in headers and some in the body, which if the Cadl followed the only-if-logical would probably be a good thing to do.

**Comment by nguerrera** [comment] 2023-01-13 18:14
Permalink for relevant cadl-autorest code since that non-permalink is already off by a few lines, I think:

https://github.com/Azure/cadl-azure/blob/b86f3fe67848d72e4bd532124538a820ca851a8f/packages/cadl-autorest/src/openapi.ts#L1373-L1375

**Comment by nguerrera** [comment] 2023-01-13 18:36
I'm going to close this issue since I think getEffectiveModelType is working as designed. However, I think it's entirely possible that as we talk about the logical-model-with-headers case we will end up wanting more or better compiler API. But I also think it would be best to track that separately if/when it arises.

**Closed by nguerrera** 2023-01-13 18:36 UTC
Labels: Needs Triage
