### ISSUE TITLE
How to distinguish between the cadl namespace and the language namespace?

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#859] opened 2022-08-12 20:07 UTC
During the most recent ARB review, there were many questions about namespacing. @bterlson explained to the ARB that namespaces in Cadl are largely for internal organization of the spec and are not really something the ARB needs to scrutinize heavily. However, the architects do routinely and deeply scrutinize language namespaces (there are times where it is the only question they care about), and so the suggestion was made to change the `namespace` keyword to `cadlNamespace` or something to differentiate it.

Another question is, how would we specify what the Java or Python namespace should be for a spec, or do we? With Swagger we use the README. Is this the purview of sidecar files or something else?

**Comment by tjprescott** [comment] 2022-08-16 21:10
At today's meeting (8/16) the archboard was very clear they want the Cadl namespace to be the canonical namespace that is carried through all clients and so forth.

**Comment by markcowl** [comment] 2022-08-19 16:14
duplicate of #1903

**Closed by markcowl** 2022-08-19 16:14 UTC
Labels: Needs Triage
