### ISSUE TITLE
Outline view only works per file?

### ISSUE THREAD

**Issue by tjprescott** [microsoft/cadl#1089] opened 2022-09-27 15:10 UTC
This may be 100% intended, but I was a little surprised and sad to see that the outline view in VSCode only seems to work on a single file at a time. So, if you have anything but a single main.cadl (for example, splitting routes and models) you only get a partial outline. If I'm in a project folder, I would like the outline view to show all logical Cadl elements as if I did a `cadl compile` and allow it to jump between files. But I don't know if that's just technically infeasible.

**Comment by timotheeguerin** [comment] 2022-09-27 18:32
There was another issue to be able to provide workspace symbols to you do do `ctrl/cmd k` to go to symbols. However the outline I think is always showing only the current document(looking at other language it never expose more than the current doc)

**Comment by markcowl** [comment] 2022-09-27 18:44
- close as by design and ensure there is an issue for workspace symbols

**Comment by nguerrera** [comment] 2022-09-27 21:42
Closing this as it's expected and just how VS Code outline view works. 

Workspace symbols now tracked by #1094.

**Closed by nguerrera** 2022-09-27 21:42 UTC
Labels: Needs Triage
