### ISSUE TITLE
OpenAPI 2 emitter does not appear to use `@exetnsion` in model definition

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#681] opened 2022-07-01 23:51 UTC
I have this definition in a Cadl file:

```
model CommonParameters {
    @doc("Target hub name, which should start with alphabetic characters and only contain alpha-numeric characters or underscore.")
    @pattern("^[A-Za-z][A-Za-z0-9_`,.[\\]]{0,127}$")
    @extension("x-ms-parameter-location", "client")
    @path
    hub: string,

    @doc("The version of the REST APIs.")
    @query
    "api-version": string
}
```

and the emitted openapi 2 is:

```
    "CommonParameters.hub": {
      "name": "hub",
      "in": "path",
      "required": true,
      "description": "Target hub name, which should start with alphabetic characters and only contain alpha-numeric characters or underscore.",
      "pattern": "^[A-Za-z][A-Za-z0-9_`,.[\\]]{0,127}$",
      "type": "string",
      "x-ms-parameter-location": "method"
    },
```

I had been expecting the value of x-ms-parameter-location to be set to `client`.

**Comment by markcowl** [comment] 2022-07-05 18:49
estimate: 3

**Comment by markcowl** [comment] 2022-07-05 19:17
closing as duplicate of #664 We don't generally allow updating existing emitted extensiosn through use of `@extension`, but need an indicator with a higher level to override the default semantics.

**Closed by markcowl** 2022-07-05 19:17 UTC
Labels: Needs Triage
