### ISSUE TITLE
Discriminated types using inheritance should scan for nested types

### ISSUE THREAD

**Issue by johanste** [microsoft/cadl#604] opened 2022-06-08 17:56 UTC
In the scenario below, there is an intermediary templated type between the "root" (base) discriminated type and the actual leaf models/implementations. However, the leaf models are not included in the discriminator mapping from the `Input` model.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5SZXN0OwoKQGRpc2NyaW1pbmF0b3IoImtpbmQiKQptb2RlbCBJbnB1dCB7Cgp9CswSVDxULCBLaW5kPiBleHRlbmRzySogIMRBOsUeOwogIC4uLiBUO8RA3WlPdXTGQMlpxhJUPFQ9e33KZ8woYWxpYXMgR3JvdXDkAJBUxHM%2BID3lAIVp5ACPOusArsYe5ACSb8VDOsphPjsKfTvId1NwZWNpZmljxTruAN5UPHt9LCAic8ciVGhpbmciPuYAjEDlAVNIdHRwLnBvc3Qgb3AgZG9fc3R1ZmYoaW7nAIkpyHU7)

**Comment by markcowl** [comment] 2022-06-16 23:11
For August this is an investigation of size '2'.  If a fix is simple, we should complete it, otherwise, close this investigation issue and file an issue to fix the root cause.

**Comment by timotheeguerin** [comment] 2022-07-11 21:11
Simplified repo https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5SZXN0OwoKQGRpc2NyaW1pbmF0b3IoImtpbmQiKQptb2RlbCBJbnB1dCB7fQrMEFQ8S2luZD4gZXh0ZW5kc8glCiAgxDw6IMQeOwrJNFNwZWNpZmljxifNNVQ8InPHHlRoaW5nIj7FbG9wIHRlc3QoKTrGJzsK

**Comment by timotheeguerin** [comment] 2022-07-11 21:22
So the issue here is that there is 2 level of `extends` and when we build the discriminator mapping we only check one level deep
If you change in the repo the 2nd `extends` with `is` [everything is working fine](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5SZXN0OwoKQGRpc2NyaW1pbmF0b3IoImtpbmQiKQptb2RlbCBJbnB1dCB7fQrMEFQ8S2luZD4gZXh0ZW5kc8glCiAgxDw6IMQeOwrJNFNwZWNpZmljxidpxzBUPCJzxxlUaGluZyI%2BxWdvcCB0ZXN0KCk6xic7Cg%3D%3D) 

Now I don't know if this is really a bug then, if we were going to check the entire nested children then we would end up with some unwanted result(if you have nested discriminator).

However I can see this being quite a bit confusing and will likely happen in the future. There could be 2 ways forward, not sure if they are actually feasible and wouldn't result in false positive:
- show some warning when using this pattern?
- look for nested children when the child is a generic.

**Comment by johanste** [comment] 2022-07-11 21:26
Yeah, obvious this was/is not. Nested discriminators is interesting, but assuming that they refer to different properties, I don't think there is any confusion/ambiguity?

**Comment by timotheeguerin** [comment] 2022-07-11 22:23
So we support nested discrimnator and those work fine,

```
Pet discriminator: kind
  Cat(kind: 'cat')
  Dog(kind: 'dog') discriminator: breed
    GermanSheperd(breed='GermanSheperd')
    Bulldog(breed='bulldog')
```

this create the following mapping 

```
Pet -> Cat or Dog
Dog -> GermanSheperd or Bulldog
```

but now using the pattern in this issue we could have that, which should according the to issue produce the same thing.
```
Pet discriminator: kind
  PetT<Kind>
    Cat(kind: 'cat')
    Dog(kind: 'dog') discriminator: breed
      GermanSheperd(breed='GermanSheperd')
      Bulldog(breed='bulldog')
```

Now we need to undestand that we need to look 2 level deep but not more. What if there are some items at different levels, this gets quite messy.

**Comment by timotheeguerin** [comment] 2022-07-12 18:33
So we actually already emit an error when you do this with the intermediate model not being a templated type 
```
import "@cadl-lang/rest";

using Cadl.Rest;

op test(): Foo;

@discriminator("kind")
model Foo {}

// Direct extends
model A extends Foo {
  kind: "A";
}

// Nested extends
model I extends Foo {}
model B extends I {
  kind: "B";
}

```

[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5SZXN0OwoKb3AgdGVzdCgpOiBGb287CgpAZGlzY3JpbWluYXRvcigia2luZCIpCm1vZGVsxCMge30KCi8vIERpcmVjdCBleHRlbmRzxyBByBDGKgogIMQ%2FOiAiQSI7CsY4TmVzdGVkzzhJzjh9xxdCyRdJzE1CxU0%3D) 

![image](https://user-images.githubusercontent.com/1031227/178568622-5e4dafbb-6497-4f2c-9956-613afef51644.png)

**Comment by timotheeguerin** [comment] 2022-09-13 16:05
Repro of the 2 cases https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKdXNpbmcgQ2FkbC5IdHRwO8wRUmVzdDsKb3AgdGVzdCgpOiBGb287CgoKQGRpc2NyaW1pbmF0b3IoImtpbmQiKQptb2RlbMQkIHsKICBuYW1lOiBzdHJpbmc7Cn0KCi8vIFVuY29tbWVudCBhbmQgeW91IGdldCB0aGUgZXhwZWN0ZWQgZXJyb3LELMZOSW5kaXJlY3QyIGV4dGVuZHPGYCDGUGJ1dCBoZXJlIGl0IGlzIGZpbmUgYXMg5ACQxBAiZGXEE2Qi5wCbyE08VD7OTwogxTQ6IFTkAKnGLUNoaWxkySfJOyJhIj4ge30%3D

**Comment by timotheeguerin** [comment] 2022-09-13 16:29
This is now a design question on if we should allow intermediate types 

Should this work?
```cadl
@discrinator("kind") model Pet {}

// This is intermediate model without discrimnator
model Feline extends Pet {}

model Cat extends Feline {kind: "cat";}
```

with nested discriminators
```cadl
@discrinator("kind") model Pet {}

// This is intermediate model without discrimnator
model Feline extends Pet {}

@discrimnator("breed")
model Cat extends Feline {kind: "cat";}

model Siamese extends Cat {breed: "siamese"}
```

this could be achieved with

**Closed** 2022-10-12 19:46 UTC
Labels: Needs Estimate, :pushpin:, WS: Language Completeness
