### ISSUE TITLE
Revisit format string design for @doc decorator

### ISSUE THREAD

**Issue by rakshith91** [microsoft/cadl#810] opened 2022-08-03 21:33 UTC
Currently, `@doc` decorator accepts an instance as a second parameter

Let's say I have two models with a slightly different documentation prose:

```
@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueModified event.")
model AppConfigurationKeyValueModifiedEventData {
  @doc("The key used to identify the key-value that was modified.")
  key?: string;
  @doc("The label, if any, used to identify the key-value that was modified.")
  label?: string;
}

@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueDeleted event.")
model AppConfigurationKeyValueDeletedEventData {
  @doc("The key used to identify the key-value that was deleted.")
  key?: string;
  @doc("The label, if any, used to identify the key-value that was deleted.")
  label?: string;
} 
```

currently a viable solution is having an object (for instance, an enum) and passing it as a second parameter to the decorator

```
enum AppConfigurationEventTypes {
  modified;
  deleted;
}

model AppConfigurationBase<TResource> {
  @doc("The key used to identify the key-value that was {name}.", TResource)
  key?: string;
  @doc("The label, if any, used to identify the key-value that was {name}.", TResource)
  label?: string;
}
@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueModified event.")
model AppConfigurationKeyValueModifiedEventData is AppConfigurationBase<AppConfigurationEventTypes.modified>;

@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueDeleted event.")
model AppConfigurationKeyValueDeletedEventData is AppConfigurationBase<AppConfigurationEventTypes.deleted>;
```

**Expected Behavior**
However, ideally passing a string directly should suffice - like below

```
model AppConfigurationBase<TResource> {
  @doc("The key used to identify the key-value that was {name}.", TResource)
  key?: string;
  @doc("The label, if any, used to identify the key-value that was {name}.", TResource)
  label?: string;
}
@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueModified event.")
model AppConfigurationKeyValueModifiedEventData is AppConfigurationBase<"modified">;

@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueDeleted event.")
model AppConfigurationKeyValueDeletedEventData is AppConfigurationBase<"deleted">;
```

**Comment by markcowl** [comment] 2022-08-05 16:14
priority: 2 (shorthand for looking at what we want to allow in the format string)

**Comment by markcowl** [comment] 2023-01-04 20:07
Closing as duplicate of #932

**Closed by markcowl** 2023-01-04 20:07 UTC
Labels: CADL Design, :pushpin:, WS: Svc Partner Adoption, WS: Language Completeness, Required for DPG 1.0
