### ISSUE TITLE
Improve service metadata implementation

### ISSUE THREAD

**Issue by bterlson** [microsoft/cadl#216] opened 2022-02-01 21:18 UTC
Areas for improvement include:
* Allow multiple service definitions per program
* Allow querying service metadata without needing the program's active projection set.

In both cases, ensuring the service metadata is keyed to a root namespace rather than a program will help.

**Comment by markcowl** [comment] 2022-11-08 01:50
closing as duplicate of #1052

**Closed by markcowl** 2022-11-08 01:50 UTC
Labels: :pushpin:, WS: Language Completeness
