### ISSUE TITLE
Adding type to the global scope can pollute a library using `using`

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1162] opened 2022-10-13 23:47 UTC
Repro  

main.cadl
```cadl
import "./lib.cadl";

// Find references for this(or rename)
model Foo {}

```
lib.cadl  (this would represent a library)
```cadl
import "./other.cadl";
namespace MyLib {
  // This is good we don't find it as a reference to the root Foo
  model Foo {}
}
```
other.cadl

```cadl
using MyLib;

model ReferenceFoo {
  foo: Foo; // This is mean to point to MyLib.Foo but the global Foo gets resolved
}
```

<img width="542" alt="image" src="https://user-images.githubusercontent.com/1031227/195731953-be68edaa-10c1-4479-9ac6-f6191abc28c9.png">

This can be result in some really bad overriding of library code.

### Global scope is scoped to a file

Any element not defined in a namespace cannot be referenced from another file.

### Using elements gets resolved before global scope

When resolving elements it should look into the using before the global scope.

### Some way to lock a library resolution

As Nick pointed out this is not a problem in csharp outside of a given project as the resolution get locked, maybe we could figure out something similar. Though the reason it probably work in csharp is each library is compiled and everything is resolved at a library scope.

**Comment by nguerrera** [comment] 2022-10-14 00:17
Very surprising, I'll take a look

**Comment by nguerrera** [comment] 2022-10-14 00:30
Hmm, I'm not sure this repro is wrong. global.Foo is found before we look for anything brought in by using. 


That ReferenceFoo really does use the global Foo:
![image](https://user-images.githubusercontent.com/75470/195735635-438a3a5c-fce3-4816-88da-410b659195b0.png)

**Comment by nguerrera** [comment] 2022-10-14 00:34
Don't understand what happened with `Model`, though in your PR. Looking

**Comment by timotheeguerin** [comment] 2022-10-14 00:35
I thought I reproed outside of my pr

**Comment by nguerrera** [comment] 2022-10-14 00:51
> Don't understand what happened with Model, though in your PR. Looking

I misunderstood the effect, it's that decorators in a lib using `Model` via using start referencing the global `Model` in the test, not that references in the test to `Model` start referencing `Cadl.Reflection.Model`

Seems find-references/rename/goto-definition are respecting same resolution as compiler, but compiler resolution is very confusing at best. IIRC, global is preferred over using in C# too, but you can't impact a compiled library that you reference at all so it doesn't lead to something quite this bad!

**Comment by timotheeguerin** [comment] 2022-10-14 00:53
updated the issue with the findings

**Comment by nguerrera** [comment] 2022-10-14 01:04
I don't think this is entirely limited to global namespace. 

I suspect that if you had a lib with definitions in `namespace A` and `using A.B` with `Foo` resolving to `A.B.Foo` normally, then someone came along and added `A.Foo`, the references would get hijacked. But it's much more severe for global because everyone is impacted.

**Comment by nguerrera** [comment] 2022-10-28 19:33
@markcowl this needs design and I think should be considered high priority to design. We don't have a proposal yet. Adding design label.

**Comment by nguerrera** [comment] 2023-01-18 16:57
> However it might come cheaper after we get this seperation of symbol resolution from the type checking that we needed for another issue.

Does anyone have a link to the other issue in question?

**Comment by nguerrera** [comment] 2023-01-18 17:01
Talked briefly with @bterlson and the different import rules are concerning. Counter-proposal for v1. Document aggressively that a library should never add types to a global namespace or to a namespace that it does not "own". This is a good guideline anyway. But the downside is that if anyone does not follow it, it can be very hard to diagnose. Can use full-qualification as workaround for offending library too.

**Comment by nguerrera** [comment] 2023-01-18 17:09
I think the most conservative guideline is every library must pick a unique namespace name and put everything there or below. I think we do this in practice. We have some cases of library with more than one namespace but no cases of one namespace reused in multiple libraries. I will check this.

**Comment by nguerrera** [comment] 2023-01-18 17:37
Another idea is to make it an error for a reference to be ambiguous between something brought in by using and something not. Today, I think the non-using one just silently wins and that's where all the confusion starts.

I've reviewed and in practice I do not find a single instance where this can come up in all the libraries we've shipped. So the guidelines above are good and then we'd have a diagnostic that someone who is a victim of a lib not following them can workaround by replacing usings with full qualification. I will need a bit more time to test and write this up. If we can agree on the general idea of only adding diagnostics and guidelines in today's design meeting, I can bring it back with a proper proposal after that.

**Comment by markcowl** [comment] 2023-01-18 18:41
- document good namespace behavior
- document 'reserved' namespaces
- add a diagnostic
  - if possible, add detail to diagnostic about library source of conflicting types

cons:
- error could be difficult for users to decipher / fix if issue is caused by conflict between shared libs

things to consider:
- linting rules for libraries
- namespace registry

**Comment by nguerrera** [comment] 2023-01-18 21:02
Will validate this with @bterlson, then create implementation issue.

**Comment by nguerrera** [comment] 2023-01-18 22:28
The proposal for the diagnostic that is basically approved pending vetting with @bterlson is basically to make this:

https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgTSB7fQoKbmFtZXNwYWNlIEIgewogIMscfQoKdXNpbmcgQjsKCsYYUSBleHRlbmRzxiI%3D

start issuing a diagnostic just like this:

https://cadlplayground.z22.web.core.windows.net/?c=bmFtZXNwYWNlIEEgewogIG1vZGVsIE0ge30KfQoKyh5C0x51c2luZyBBO8cJQjsKCsYhUSBleHRlbmRzxis%3D

In other words, generalize things so that using+in-scope can create same ambiguous reference error as two usings.

We would still need the guidelines so that you don't cause users to see this when combining two libraries together that pollute global or each other's namespace.

I think this is an improvement, it's not obvious to me that the global (or generally in-scope-without-using should silently win over using and asking for full qualification in that case as well seems fine. 

That said, C# does have the same behavior as we do now:

https://sharplab.io/#v2:D4AQDABAgg3AsAKEQZwKYEMA2qAmEQBMEAshAN4C+iiAdugLarIAO6AxqtOYhL/kaUqIqSUYQgBFCAC4S5CkA===

But:
1. It's less consequential in C# due to distributing pre-compiled libraries 

2. It's still confusing to me in C# and we still tell people the same guideline to use a scheme to keep their namespace unique (Company.Technology) and to never put anything public in global namespace.

**Closed** 2023-01-26 22:45 UTC
Labels: bug, CADL Design, :pushpin:, WS: Language Completeness
