### ISSUE TITLE
@@doc() decorator does not override existing doc

### ISSUE THREAD

**Issue by pshao25** [microsoft/cadl#1544] opened 2023-01-16 09:38 UTC
A.cadl
```
@route("/protocol")
@doc("Initial doc.")
@get
op protocol(): Model;
```
B.cadl
```
import "./A.cadl";
@@doc(protocol, "Update doc.")
```
Actual: The description is "Initial doc."
Our expectation is: The description is "Update doc." So that we could modify the metadata from A.cadl in B.cadl.

Playground here: https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0K0xtvcGVuYXBpzR5henVyZS10b29scy%2FFKmRwZ8QhDQpAc2VydmljZVRpdGxlKCJDb252ZW5pZW5jZSBtZXRob2QgaW4gQ0FETCIpyi1WZXJzaW9uKCIwLjEuMMUaZG9jKCLEKCBwcm9qZWN0IHRvIHRlc3QgY9FTLsQybmFtZXNwYWNlIMt0SW5DYWRs5QCZdXNpbmcgxA8uSHR0cDvNElJlc3TJEkHkAN0uRFBHxTjmAIpBIG1vZGVsxWrFCiBNxQZ7DQogICAgaWQ6IHN0cmluZzsNCn3FN8U4cHJvdG9jb2wsICJVcGRhdGUgZG9jxUUNCkByb3V0ZSgiL8gl6gD4SW5pdGlhbMktQGdldA0Kb3DkAQzFKygpOuYAgTsNCg%3D%3D

**Comment by markcowl** [comment] 2023-01-19 17:56
duplicate of: #1541

**Closed by markcowl** 2023-01-19 17:56 UTC
Labels: Needs Triage
