### ISSUE TITLE
Create a sample Cadl library that consumes Cadl core as an npm library

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#540] opened 2022-05-13 17:25 UTC
We currently use git submodules to consume the Cadl core in our own libraries, but for external use we should encourage using the core npm package.  We will need a good example library that uses this pattern as part of public beta.

**Comment by timotheeguerin** [comment] 2022-05-16 15:23
So any of our libraries should be able to be copied as they are and used outside without any changes(Apart from them having changes not yet available in the published version).

As Nick was suggesting I think what could be valuable would be do have a `cadl init library`

**Comment by markcowl** [comment] 2022-05-17 19:13
These two things may be orthogonal.  It is good to have a cadl init library, but it should also be possible for folks to use npm init themselves to consume cadl without having to understand our repo structure.  We might have a document about converting any of our samples, or we might have a specific documentary sample that has an appropriate package.json, independent from the one in the cadl-samples package.

**Comment by markcowl** [comment] 2022-06-03 16:08
Clarified that this is in support of a tutorial for extending cadl through libraries.

**Comment by markcowl** [comment] 2022-06-03 16:10
Closing as duplicate of #548

**Closed by markcowl** 2022-06-03 16:10 UTC
