### ISSUE TITLE
Tag annotation adds to tags both operation and top level

### ISSUE THREAD

**Issue by niku** [microsoft/cadl#413] opened 2022-04-06 05:10 UTC
When I add tag annotations on cadl, tags are added both operation and top level tags on openapi.
Is it intended behavior?

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGm9wZW5hcGndHTMiOwoKdXNpbmcgQ2FkbC5IdHRwOwoKQHRhZygidGFnLWZvci1teW5hbWVzcGFjZSIpCskMIE15TskMewogIEBnZXTEB3JvdXRlKCIvbXlwYXRoIinEFM9Rb3BlcmF0aW9uMcUfb3AgTXlPyRQoKTogc3RyaW5nOwrEPXBvc99Z0lky01kyzFl9Cg%3D%3D)

```cadl
import "@cadl-lang/rest";
import "@cadl-lang/openapi";
import "@cadl-lang/openapi3";

using Cadl.Http;

@tag("tag-for-mynamespace")
namespace MyNamespace {
  @get
  @route("/mypath")
  @tag("tag-for-myoperation1")
  op MyOperation1(): string;

  @post
  @route("/mypath")
  @tag("tag-for-myoperation2")
  op MyOperation2(): string;
}
```

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "(title)",
    "version": "0000-00-00"
  },
  "tags": [
    {
      "name": "tag-for-mynamespace"
    },
    {
      "name": "tag-for-myoperation1"
    },
    {
      "name": "tag-for-myoperation2"
    }
  ],
  "paths": {
    "/mypath": {
      "get": {
        "operationId": "MyNamespace_MyOperation1",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "tag-for-mynamespace",
          "tag-for-myoperation1"
        ]
      },
      "post": {
        "operationId": "MyNamespace_MyOperation2",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "tag-for-mynamespace",
          "tag-for-myoperation2"
        ]
      }
    }
  },
  "components": {}
}
```

**Comment by mikekistler** [comment] 2022-04-06 18:32
Yes that is the intended behavior.  The `tags` at the top level can be used to specify metadata for each tag, such as a description or link to external docs, whereas the `tags` at the operation level are simply the tag names.  We don't have a mechanism for specifying the tag metadata in Cadl at the moment, but that would be a useful addition.

It's also worth noting that some linters for OpenAPI such as [Spectral](https://meta.stoplight.io/docs/spectral/ZG9jOjYx-overview) check that tags specified at the operation level are defined in the top-level `tags` array ([operation-tag-defined](https://meta.stoplight.io/docs/spectral/ZG9jOjExNw-open-api-rules#operation-tag-defined)).

Is there a reason _not_ to include them in the top-level `tags`?

**Comment by markcowl** [comment] 2022-04-13 21:27
@niku closing as answered, please reopen if you think the behavior should be different.

**Closed by markcowl** 2022-04-13 21:27 UTC
