### ISSUE TITLE
How to generate example in OpenAPI emitter

### ISSUE THREAD

**Issue by kesavkolla** [microsoft/cadl#1478] opened 2022-12-24 18:15 UTC
In OpenAPI we can specify example to model properties. Example:

```yaml
Pet:
  required:
    - name
    - photoUrls
  type: object
  properties:
    id:
      type: integer
      format: int64
      example: 10
    name:
      type: string
      example: doggie
    category:
      $ref: "#/components/schemas/Category"
    photoUrls:
      type: array
      xml:
        wrapped: true
      items:
        type: string
        xml:
          name: photoUrl
```

Is there any decorator to emit the example?

**Comment by timotheeguerin** [comment] 2022-12-27 15:18
We do not unfortunately have this, we have a design issue to solve this at the core level here https://github.com/microsoft/cadl/issues/514

**Comment by markcowl** [comment] 2023-01-04 22:45
Closing as duplicate of #514

**Closed by markcowl** 2023-01-04 22:45 UTC
Labels: Needs Triage, customer-reported
