### ISSUE TITLE
Using model input in @doc gives "undefined" instead of value

### ISSUE THREAD

**Issue by l0lawrence** [microsoft/cadl#1376] opened 2022-12-06 17:22 UTC
Based off of TDoc here:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/property-types/main.cadl 

[Playground Link](https://cadlplayground.z22.web.core.windows.net/prs/1359/?c=QHNlcnZpY2Uoe3RpdGxlOiJIZWxsbyIsIHZlcnNpb246IjIwMTgtMDEtMDEifSkNCkBkb2MoIkRlc2NyaWJlcyB0aGUgc2NoZW1hIG9mxQ5BenVyZSBTdG9yYWdlIGV2ZW50cyBwdWJsaXNoZWQgdG%2FHIkXEGiBHcmlkLiBUaGlzIGNvcnJlc3BvbmRzxCbETERhdGEgcHJvcGVydHnEYWFuxjjEN8UJLiIpDQpuYW1lc3BhY8l3ew0KDQogIG1vZGVsIHNvbWV0aGluZzxUZG9jIGV4dGXEY3N0cmluZz57xCkgIOYA2CBFeHBlY3RlZCAne2RvY30nICIsIMQKOsQ75AEAxCxzPzrGPTvEEH3NbDTKYMl3ImjlAVU%2Be30NCn0%3D)

**Comment by timotheeguerin** [comment] 2022-12-06 19:14
Problem seems to be that we check properties on the js object instead of properties on the cadl model.

This feels like this also might be the correct behavior when we'll have "object" types. Having string interpolation in cadl also would solve that.

**Comment by markcowl** [comment] 2022-12-08 17:27
associate with interpolation in @doc item #932

**Comment by markcowl** [comment] 2022-12-08 17:52
Closing as duplicate of #932

**Closed by markcowl** 2022-12-08 17:52 UTC
Labels: Needs Triage
