### ISSUE TITLE
@visibility("update") vs. @visibility("write") confusion

### ISSUE THREAD

**Issue by tg-msft** [microsoft/cadl#1255] opened 2022-11-09 17:25 UTC
During the review of https://github.com/Azure/azure-rest-api-specs-pr/issues/7483, there was a some confusion on `update` vs. `write`.  I _think_ I heard that `write` means "write once during initialization" and `update` means "write as many times as you want."  I tried to verify that understanding at https://microsoft.github.io/cadl/docs/standard-library/built-in-decorators/#visibility-decorators but we don't clearly document the allowed values or what they mean.

If I've got a correct understanding, I think it would feel more natural to change `write` => `init` and then `update` => `write` to better match the intuition of the average developer.

**Comment by markcowl** [comment] 2022-11-09 20:00
I think this is a duplicate of #1175   The POR is to deprecate 'write' visibility in favor of 'update' and 'create'

**Comment by nguerrera** [comment] 2022-11-09 22:02
Yes, the deprecation is in. visibility("write") should not be used and will result in a warning starting in release coming out shortly.

**Closed by nguerrera** 2022-11-09 22:02 UTC
Labels: Needs Triage

**Comment by tg-msft** [comment] 2022-11-09 22:30
Can you please update the docs at https://microsoft.github.io/cadl/docs/standard-library/built-in-decorators/#visibility-decorators to list all the available options and describe their semantics as part of that change?

**Comment by nguerrera** [comment] 2022-11-09 23:29
Yes, #298 tracks improving documentation.

Could use more detail and proximity to decorator docs, but see https://microsoft.github.io/cadl/docs/standard-library/rest/operations/#automatic-visibility for the well-known visibilities used by the REST library.

**Comment by nguerrera** [comment] 2022-11-09 23:35
Put up https://github.com/microsoft/cadl/pull/1258 to at least correct that right away and more improvements will come to the docs with #298
